version: '3'
services:
  app:
    build: "app"
    ports:
     - "5000:5000"
  redis:
    image: "redis:5.0"
    ports:
     - "6379:6379"
  mysql:
    image: "mysql:5.7"
    volumes:
     - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
     - "3306:3306"
    environment:
     MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
     MYSQL_DATABASE: "experiment"






